slam_toolbox:
  ros__parameters:
    # Plugin params (keep optimized)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    # ROS Parameters (adjusted for real-time performance)
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02  # 50Hz odometry
    map_update_interval: 2.0        # More frequent updates
    resolution: 0.05
    max_laser_range: 8.0            # Match your LiDAR's actual max range
    minimum_time_interval: 0.05     # Process scans faster (0.05s = 20Hz)
    transform_timeout: 0.1          # Increased timeout tolerance
    tf_buffer_duration: 10.0        # Reduced from 30s
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Processing optimization
    processing_threads: 2           # Utilize multiple cores
    scan_buffer_size: 30            # Increased from 10
    message_buffer_size: 50         # Buffer more incoming scans

    # Scan matching adjustments
    use_scan_matching: true
    use_scan_barycenter: false      # Faster processing
    minimum_travel_distance: 0.2    # Reduced from 0.5
    minimum_travel_heading: 0.2     # Reduced from 0.5
    link_scan_maximum_distance: 2.0 # Increased from 1.5

    # Loop closing optimization
    do_loop_closing: true
    loop_search_maximum_distance: 5.0  # Increased from 3.0
    loop_match_minimum_chain_size: 5   # Reduced from 10
    loop_match_minimum_response_coarse: 0.25  # Reduced from 0.35

    # Correlation parameters
    correlation_search_space_dimension: 0.3  # Reduced from 0.5
    correlation_search_space_resolution: 0.02
    loop_search_space_resolution: 0.1        # Reduced precision

    # Performance-critical parameters
    distance_variance_penalty: 0.3       # Reduced from 0.5
    angle_variance_penalty: 0.8          # Reduced from 1.0
    coarse_search_angle_offset: 0.1745   # ~10 degrees (reduced from 20)
    coarse_angle_resolution: 0.0523      # ~3 degrees (reduced from 2)